# Generated by Django 5.0.7 on 2024-07-30 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_remove_userprofile_additional_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='portfolio',
        ),
    ]
