# Generated by Django 5.0.7 on 2024-07-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techhub', '0002_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('desenvolvimento web', 'DEV WEB'), ('desenvolvimento mobile', 'DEV MOBILE'), ('desenvolvimento de jogos', 'DEV DE JOGOS')], default='', max_length=100),
        ),
    ]
