# Generated by Django 5.0.7 on 2024-07-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techhub', '0003_projects_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('DEV WEB', 'desenvolvimento web'), ('desenvolvimento mobile', 'DEV MOBILE'), ('desenvolvimento de jogos', 'DEV DE JOGOS')], default='', max_length=100),
        ),
    ]
