# Generated by Django 5.0.7 on 2024-07-30 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techhub', '0004_projects_publish_alter_projects_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
