# Generated by Django 5.0.7 on 2024-07-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techhub', '0005_projects_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('desenvolvimento web', 'DEV WEB'), ('DEV MOBILE', 'desenvolvimento mobile'), ('DEV DE JOGOS', 'desenvolvimento de jogos')], default='', max_length=100),
        ),
    ]
