# Generated by Django 5.0.7 on 2024-07-30 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techhub', '0006_projects_image_alter_projects_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('desenvolvimento web', 'DESENVOLVIMENTO WEB'), ('ANÁLISE DE DADOS', 'analise de dados'), ('segurança da informação', 'SEGURANÇA DA INFORMAÇÃO'), ('inteligência artificial', 'INTELIGÊNCIA ARTIFICIAL')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='articles',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='articles',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('desenvolvimento web', 'DESENVOLVIMENTO WEB'), ('ANÁLISE DE DADOS', 'analise de dados'), ('segurança da informação', 'SEGURANÇA DA INFORMAÇÃO'), ('inteligência artificial', 'INTELIGÊNCIA ARTIFICIAL')], default='', max_length=100),
        ),
    ]
