# Generated by Django 5.0.7 on 2024-07-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techhub', '0007_articles_category_articles_data_articles_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('DESENVOLVIMENTO WEB', 'desenvolvimento web'), ('analise de dados', 'ANÁLISE DE DADOS'), ('SEGURANÇA DA INFORMAÇÃO', 'segurança da informação'), ('INTELIGÊNCIA ARTIFICIAL', 'inteligência artificial')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('DESENVOLVIMENTO WEB', 'desenvolvimento web'), ('analise de dados', 'ANÁLISE DE DADOS'), ('SEGURANÇA DA INFORMAÇÃO', 'segurança da informação'), ('INTELIGÊNCIA ARTIFICIAL', 'inteligência artificial')], default='', max_length=100),
        ),
    ]
