# Generated by Django 5.0.7 on 2024-07-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techhub', '0010_alter_articles_category_alter_projects_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('DESENVOLVIMENTO WEB', 'desenvolvimento web'), ('ANÁLISE DE DADOS', 'analise de dados'), ('segurança da informação', 'SEGURANÇA DA INFORMAÇÃO'), ('inteligência artificial', 'INTELIGÊNCIA ARTIFICIAL')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('DESENVOLVIMENTO WEB', 'desenvolvimento web'), ('ANÁLISE DE DADOS', 'analise de dados'), ('segurança da informação', 'SEGURANÇA DA INFORMAÇÃO'), ('inteligência artificial', 'INTELIGÊNCIA ARTIFICIAL')], default='', max_length=100),
        ),
    ]
